FROM cgr.dev/chainguard/python:latest-dev
WORKDIR /app
COPY requirements.txt .
RUN --mount=type=cache,target=/pip-cache,id=pip,uid=65532 \
    pip install --cache-dir=/pip-cache -r requirements.txt
COPY . .
