ARG BUILDER_IMAGE="oven/bun:1"
ARG RUNTIME_IMAGE="oven/bun:1-slim"

FROM ${BUILDER_IMAGE}
WORKDIR /app
COPY package.json server.js ./
RUN --mount=type=secret,id=bunfig,target=/app/bunfig.toml \
    bun install 
EXPOSE 3000
CMD ["bun", "run", "server.js"]
