---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster 
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: cgr.dev/ky-rafaels.example.com/iamguarded-charts
    chart: redis-cluster 
    targetRevision: 12.0.1 
    helm:
      passCredentials: true
      values: |
        global:
          org: ky-rafaels.example.com
  destination:
    name: "in-cluster"
    namespace: 'redis-cluster'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true