services:
  nginx-example-0:
    image: nginx
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
