events {}
http {
    server {
        listen       9090;
        server_name  localhost;
        root /usr/share/custom/html;
        index index.html;
    }
    # Refuse anything that doesn't match the hostname above
    server {
        listen      9090 default_server;
        server_name _;
        return      444;
    }