---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gw-class
spec:
  controllerName: example.com/gateway-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: gw-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-httproute
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: pathPrefix
            value: /chat
      backendRefs:
      - name: chat-app-service
        port: 8080
