apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-templates
data:
  default.conf.template: |
    server {
        listen 80;
        server_name _;

        location /pod {
          return 200 "This is ${POD_NAME}!";
          add_header Content-Type text/plain;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: templates
          configMap:
            name: nginx-templates
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: templates
              mountPath: /etc/nginx/templates

